SET SERVEROUTPUT ON;

CREATE TABLE AUTHOR (AUTHOR_ID NUMBER,AUTHOR_NAME VARCHAR2(50));

INSERT INTO AUTHOR VALUES (101, 'Farhan');
INSERT INTO AUTHOR VALUES (102, 'Meena');
INSERT INTO AUTHOR VALUES (103, 'Karthik');

COMMIT;

SELECT UPPER(AUTHOR_NAME) FROM AUTHOR;

SELECT LOWER(AUTHOR_NAME) FROM AUTHOR;

SELECT INITCAP(AUTHOR_NAME) FROM AUTHOR;

SELECT AUTHOR_NAME, LENGTH(AUTHOR_NAME) FROM AUTHOR;

SELECT SUBSTR(AUTHOR_NAME, 1, 3) FROM AUTHOR;

SELECT CONCAT(AUTHOR_NAME, ' Banu') FROM AUTHOR;

SELECT REVERSE(AUTHOR_NAME) FROM AUTHOR;
