CREATE TABLE DOCTOR (DOC_ID NUMBER,DOC_NAME VARCHAR2(50),HOSPITAL_ID NUMBER);

INSERT INTO DOCTOR VALUES (101, 'Arun', 10);
INSERT INTO DOCTOR VALUES (102, 'Meena', 20);
INSERT INTO DOCTOR VALUES (103, 'Rahul', 30);
INSERT INTO DOCTOR VALUES (104, 'Divya', 40);

CREATE TABLE HOSPITAL (HOSPITAL_ID NUMBER,HOSPITAL_NAME VARCHAR2(50));

INSERT INTO HOSPITAL VALUES (10, 'Apollo');
INSERT INTO HOSPITAL VALUES (20, 'Kauvery');
INSERT INTO HOSPITAL VALUES (30, 'Fortis');
INSERT INTO HOSPITAL VALUES (50, 'MIOT');

COMMIT;

SELECT DOCTOR.DOC_ID, DOCTOR.DOC_NAME, HOSPITAL.HOSPITAL_NAME
FROM DOCTOR
INNER JOIN HOSPITAL
ON DOCTOR.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID;

SELECT DOCTOR.DOC_ID, DOCTOR.DOC_NAME, HOSPITAL.HOSPITAL_NAME
FROM DOCTOR
LEFT JOIN HOSPITAL
ON DOCTOR.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID;

SELECT DOCTOR.DOC_ID, DOCTOR.DOC_NAME, HOSPITAL.HOSPITAL_NAME
FROM DOCTOR
RIGHT JOIN HOSPITAL
ON DOCTOR.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID;

SELECT DOCTOR.DOC_ID, DOCTOR.DOC_NAME, HOSPITAL.HOSPITAL_NAME
FROM DOCTOR
FULL OUTER JOIN HOSPITAL
ON DOCTOR.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID;
