CREATE TABLE THEATRE (
    TICKET_ID NUMBER CONSTRAINT PK_TICKET PRIMARY KEY,
    MOVIE_NAME VARCHAR2(50) CONSTRAINT NN_MOVIE NOT NULL,
    SEAT_NO VARCHAR2(10) CONSTRAINT UQ_SEAT UNIQUE,
    PRICE NUMBER CONSTRAINT CHK_PRICE CHECK (PRICE >= 100),
    LOCATION VARCHAR2(30) DEFAULT 'Chennai'
);

INSERT INTO THEATRE
VALUES (101, 'Avatar', 'A1', 200, 'Chennai');

INSERT INTO THEATRE
VALUES (102, 'Titanic', 'A2', 300, 'Madurai');

COMMIT;

SELECT * FROM THEATRE;
