SET SERVEROUTPUT ON;

CREATE TABLE BOOK_A (ID NUMBER,NAME VARCHAR2(30));

INSERT INTO BOOK_A VALUES (1, 'Python');
INSERT INTO BOOK_A VALUES (2, 'Java');
INSERT INTO BOOK_A VALUES (3, 'Oracle');

CREATE TABLE BOOK_B (ID NUMBER,NAME VARCHAR2(30));

INSERT INTO BOOK_B VALUES (2, 'Java');
INSERT INTO BOOK_B VALUES (3, 'Oracle');
INSERT INTO BOOK_B VALUES (4, 'Cloud');

COMMIT;

SELECT ID, NAME FROM BOOK_A
UNION
SELECT ID, NAME FROM BOOK_B;

SELECT ID, NAME FROM BOOK_A
UNION ALL
SELECT ID, NAME FROM BOOK_B;

SELECT ID, NAME FROM BOOK_A
INTERSECT
SELECT ID, NAME FROM BOOK_B;

SELECT ID, NAME FROM BOOK_A
MINUS
SELECT ID, NAME FROM BOOK_B;
