CREATE TABLE SHIP (SHIP_ID NUMBER,SHIP_NAME VARCHAR2(50),CAPACITY NUMBER);

INSERT INTO SHIP VALUES (301, 'Ocean Star', 1200);
INSERT INTO SHIP VALUES (302, 'Sea Queen', 1800);
INSERT INTO SHIP VALUES (303, 'Blue Wave', 1500);
INSERT INTO SHIP VALUES (304, 'Sky Pearl', 2200);
INSERT INTO SHIP VALUES (305, 'Ocean King', 1300);

COMMIT;

SELECT SUM(CAPACITY) AS TOTAL_CAPACITY
FROM SHIP;

SELECT AVG(CAPACITY) AS AVERAGE_CAPACITY
FROM SHIP;

SELECT COUNT(CAPACITY) AS TOTAL_SHIPS
FROM SHIP;

SELECT MAX(CAPACITY) AS HIGHEST_CAPACITY
FROM SHIP;

SELECT MIN(CAPACITY) AS LOWEST_CAPACITY
FROM SHIP;
